[functions.social-blade]
verify_jwt = false

[functions.fetch-media-kit-public]
verify_jwt = false

[functions.fetch-social-stats]
verify_jwt = false

[functions.sync-hubspot-contact]
verify_jwt = false
