project_id = "owahoewxipxhlbmfykmf"

[functions.create-payment]
verify_jwt = true

[functions.ai-helper]
verify_jwt = true

[functions.verify-payment]
verify_jwt = false

[functions.fetch-social-blade]
verify_jwt = true

[functions.fetch-social-blade-gated]
verify_jwt = true

[functions.fetch-social-stats]
verify_jwt = true

[functions.sync-hubspot-contact]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.fetch-media-kit-public]
verify_jwt = false

[functions.sync-stripe-status]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.send-test-email]
verify_jwt = false

[functions.auth-email]
verify_jwt = false
